name:                spoopy
version:             0.1.0.0
github:              "yourfin/spoopy"
license:             BSD3
author:              "YourFin"
maintainer:          "d.junkpobox+git@gmail.com"
copyright:           "YourFin"

extra-source-files:
- README.md
- ChangeLog.md


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yourfin/spoopy#readme>

dependencies:
- base >= 4.7 && < 5
- warp >=3.3 && <4
- wai >=3.2 && <4
- blaze-html >=0.9 && <0.10
- http-types
- optparse-applicative >= 0.16.1 && <0.17
- directory >= 1.3 && <2
- bytestring >=0.10 && <0.11
- unix >= 2.7 && <3
- containers >= 0.6 && <0.7
- filepath >= 1.4 && <2
- data-default >= 0.7.1 && <0.8
- polysemy >= 1.6 && < 2
- polysemy-plugin >= 0.4

ghc-options: -O2 -flate-specialise -fspecialise-aggressively
default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - OverloadedStrings
  - MultiWayIf
  - LambdaCase

library:
  source-dirs: src

executables:
  spoopy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # Language extensions
    dependencies:
    - spoopy

tests:
  spoopy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spoopy
